on:
  push:
    branches:
      - master
name: Deploy master branch
jobs:
  deployAWS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install NPM packages
        run: npm install
      - name: Deploy sls function
        working-directory: ./services/auth
      - uses: serverless/github-action@master
        with:
          args: deploy
          env:
          # or if using AWS creds directly
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
