on:
  push:
    branches:
      - master
name: Deploy master branch
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: npm install
      - name: serverless deploy
        uses: serverless/github-action@master
        with:
          args: AWS_USER_POOL_ID='${{secrets.AWS_USER_POOL_ID}}' AWS_ACC_KEY_ID='${{secrets.AWS_ACC_KEY_ID}}' AWS_SECRET='${{secrets.AWS_SECRET}}' AWS_CLIENT_ID='${{secrets.AWS_CLIENT_ID}}' deploy
        env:
          # SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          # or if using AWS creds directly
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
