on:
  push:
    branches:
      - master
name: Deploy master branch
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: npm install
  deploy:
    name: serverless deploy
    runs-on: ubuntu-latest
    steps:
      - run: cd ./services/auth
      - uses: serverless/github-action@master
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
