on:
  push:
    branches:
      - master
name: Deploy master branch
jobs:
  install:
    name: install npm depends
    runs-on: ubuntu-latest
    uses: actions/checkout@master
    run: npm install
  deploy:
    steps:
      - name: serverless deploy
        working-directory: ./services/auth
        uses: serverless/github-action@master
        with:
          args: deploy
          env:
          # or if using AWS creds directly
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
